[Interface]
Address = ${wireguard.interface.address}
PrivateKey = ${wireguard.interface.private_key}
ListenPort = ${wireguard.interface.listen_port}

%{ for peer in wireguard.peers }
[Peer]
PublicKey = ${peer.public_key}
AllowedIPs = ${peer.allowed_ips}
Endpoint = ${peer.endpoint}
PersistentKeepalive = ${peer.persistent_keepalive}
%{ endfor ~}